# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/s03760/Toshokan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/s03760/Toshokan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/s03760/Toshokan/CMakeFiles /Users/s03760/Toshokan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/s03760/Toshokan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hakase/interrupt/test/interrupt.bin

# Build rule for target.
hakase/interrupt/test/interrupt.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hakase/interrupt/test/interrupt.bin
.PHONY : hakase/interrupt/test/interrupt.bin

# fast build rule for target.
hakase/interrupt/test/interrupt.bin/fast:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build
.PHONY : hakase/interrupt/test/interrupt.bin/fast

#=============================================================================
# Target rules for targets named generate_wrappers

# Build rule for target.
generate_wrappers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_wrappers
.PHONY : generate_wrappers

# fast build rule for target.
generate_wrappers/fast:
	$(MAKE) -f CMakeFiles/generate_wrappers.dir/build.make CMakeFiles/generate_wrappers.dir/build
.PHONY : generate_wrappers/fast

hakase/elf_loader/hakase.o: hakase/elf_loader/hakase.cc.o

.PHONY : hakase/elf_loader/hakase.o

# target to build an object file
hakase/elf_loader/hakase.cc.o:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/elf_loader/hakase.cc.o
.PHONY : hakase/elf_loader/hakase.cc.o

hakase/elf_loader/hakase.i: hakase/elf_loader/hakase.cc.i

.PHONY : hakase/elf_loader/hakase.i

# target to preprocess a source file
hakase/elf_loader/hakase.cc.i:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/elf_loader/hakase.cc.i
.PHONY : hakase/elf_loader/hakase.cc.i

hakase/elf_loader/hakase.s: hakase/elf_loader/hakase.cc.s

.PHONY : hakase/elf_loader/hakase.s

# target to generate assembly for a file
hakase/elf_loader/hakase.cc.s:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/elf_loader/hakase.cc.s
.PHONY : hakase/elf_loader/hakase.cc.s

hakase/interrupt.o: hakase/interrupt.cc.o

.PHONY : hakase/interrupt.o

# target to build an object file
hakase/interrupt.cc.o:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/interrupt.cc.o
.PHONY : hakase/interrupt.cc.o

hakase/interrupt.i: hakase/interrupt.cc.i

.PHONY : hakase/interrupt.i

# target to preprocess a source file
hakase/interrupt.cc.i:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/interrupt.cc.i
.PHONY : hakase/interrupt.cc.i

hakase/interrupt.s: hakase/interrupt.cc.s

.PHONY : hakase/interrupt.s

# target to generate assembly for a file
hakase/interrupt.cc.s:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/interrupt.cc.s
.PHONY : hakase/interrupt.cc.s

hakase/interrupt/test/hakase.o: hakase/interrupt/test/hakase.cc.o

.PHONY : hakase/interrupt/test/hakase.o

# target to build an object file
hakase/interrupt/test/hakase.cc.o:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/interrupt/test/hakase.cc.o
.PHONY : hakase/interrupt/test/hakase.cc.o

hakase/interrupt/test/hakase.i: hakase/interrupt/test/hakase.cc.i

.PHONY : hakase/interrupt/test/hakase.i

# target to preprocess a source file
hakase/interrupt/test/hakase.cc.i:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/interrupt/test/hakase.cc.i
.PHONY : hakase/interrupt/test/hakase.cc.i

hakase/interrupt/test/hakase.s: hakase/interrupt/test/hakase.cc.s

.PHONY : hakase/interrupt/test/hakase.s

# target to generate assembly for a file
hakase/interrupt/test/hakase.cc.s:
	$(MAKE) -f CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/build.make CMakeFiles/hakase/interrupt/test/interrupt.bin.dir/hakase/interrupt/test/hakase.cc.s
.PHONY : hakase/interrupt/test/hakase.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hakase/interrupt/test/interrupt.bin"
	@echo "... generate_wrappers"
	@echo "... hakase/elf_loader/hakase.o"
	@echo "... hakase/elf_loader/hakase.i"
	@echo "... hakase/elf_loader/hakase.s"
	@echo "... hakase/interrupt.o"
	@echo "... hakase/interrupt.i"
	@echo "... hakase/interrupt.s"
	@echo "... hakase/interrupt/test/hakase.o"
	@echo "... hakase/interrupt/test/hakase.i"
	@echo "... hakase/interrupt/test/hakase.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

