version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - format
      - build_python2
      - build_python3
      - doccheck
      - check_dockerimage:
          filters:
            branches:
              only:
                - master
  nightly_workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *" # UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - format
      - build_python2
      - build_python3
      - doccheck
jobs:
  build_python2:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y make bash
            pyenv install -s 2.7.12
            pyenv global 2.7.12
            pip install scons
      - run:
          command: |
            scons test -j3
  build_python3:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y make bash
            pyenv install -s 3.5.2
            pyenv global 3.5.2
            pip install scons
      - run:
          command: |
            scons test -j3
  format:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            pyenv install -s 3.5.2
            pyenv global 3.5.2
            pip install scons
      - run:
          command: |
            scons CI=1 format
  doccheck:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y rsync
            sudo pip install scons jinja2 pyyaml
      - run:
          command: |
            scons generate
            scons doccheck
  check_dockerimage:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            sudo pip install scons
      - run:
          command: |
            if [[ $CIRCLE_SHELL_ENV =~ "localbuild" ]]; then
               sudo scons imagecheck
            else
               scons imagecheck
            fi 
      
#TODO: should be refactored using YAML anchor & alias