version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python2
      - build_python3
jobs:
  build_python2:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python python-pip make bash
            pip install scons
      - run:
          command: |
            scons format
      - run:
          command: |
            scons test -j3
  build_python3:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python3 python3-pip make bash
            pip install scons
      - run:
          command: |
            scons format
      - run:
          command: |
            scons test -j3

#TODO: should be refactored using YAML anchor & alias