version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python2
      - build_python3
      - doccheck
  nightly_workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *" # UTC
          filters:
            branches:
              only:
                - master
    jobs:
      - build_python2
      - build_python3
      - doccheck
jobs:
  build_python2:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python python-pip make bash
            pip install scons
      - run:
          command: |
            scons CI=1 format
      - run:
          command: |
            scons test -j3
  build_python3:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python3 python3-pip make bash
            pip install scons
      - run:
          command: |
            scons CI=1 format
      - run:
          command: |
            scons test -j3
  doccheck:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python3 python3-pip make bash rsync git
            pip install scons jinja2 pyyaml
      - run:
          command: |
            scons doccheck
#TODO: should be refactored using YAML anchor & alias