version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            apk --update add python py-pip make bash
            pip install scons
      - run:
          command: |
            scons CI=1 format
      - run:
          command: |
            scons CI=1 test
