version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python2
      - build_python3
jobs:
  build_python2:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python python-pip make bash
            pip install scons
      - run:
          command: |
            scons CI=1 format
      - restore_cache:
          keys:
            - docker-buildcache-{{ .Branch }}-python2
      - run:
          command: if test -d .docker_images; then cd .docker_images; for f in `find . -name '*.tar'`; do docker load -i $f; done; fi
      - run:
          command: |
            scons build_huge_docker_images -j3
      - save_cache:
          key: docker-buildcache-{{ .Branch }}-python2-{{ epoch }}
          paths:
              - .sconsign.dblite
              - .docker_images
      - run:
          command: |
            scons test -j3
  build_python3:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt install -y python3 python3-pip make bash
            pip install scons
      - run:
          command: |
            scons CI=1 format
      - restore_cache:
          keys:
            - docker-buildcache-{{ .Branch }}-python3
      - run:
          command: if test -d .docker_images; then cd .docker_images; for f in `find . -name '*.tar'`; do docker load -i $f; done; fi
      - run:
          command: |
            scons build_huge_docker_images -j3
      - save_cache:
          key: docker-buildcache-{{ .Branch }}-python3-{{ epoch }}
          paths:
              - .sconsign.dblite
              - .docker_images
      - run:
          command: |
            scons test -j3
#TODO: should be refactored using YAML anchor & alias