version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            apk --update add make bash
      - run:
          command: |
            make CI=true format
      - run:
          command: |
            make CI=true test
