#!python
Import('hakase_env friend_env lib')

friend_env['LINKFLAGS']+=' -T {0}/friend.ld'.format(Dir('.').abspath)

friend = friend_env.Program(target='friend.bin', source=['friend_boot.S'])
friend_env.Depends(friend, 'friend.ld')

friend_obj = friend_env.Command('friend_bin.o', [friend],
    'bin/objcopy -I binary -O elf64-x86-64 -B i386:x86-64 $SOURCES $TARGET')
friend_env.Depends(friend_obj, '#bin/objcopy')

target = hakase_env.Program(target='#build/boot', source=[friend_obj, "hakase.cc", "hakase.ld"], LIBS=['hakase'])
hakase_env.Depends(target, lib)

Return('target')
