#!/bin/sh
for i in `seq 30`; do
    if sh -c "rsync --list-only $1: > /dev/null 2>&1"; then
        exit 0
    fi
    sleep 1;
done
echo "error: failed to access to qemu container. Please check if it's running."
exit 1
